hash-format = "sha256"

[[files]]
file = "config/com.yuushya/client_config.json"
hash = "a5068b44183cf05a773c6119c13cd8bda95d05ef566f83eaab508f4fe156ec65"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "810585d09b736b2a4aebc5757321a46f9545d23118d9029fce1f1a0d1c007253"

[[files]]
file = "config/defaultoptions/servers.dat"
hash = "92292ec662e8f3245bf4d18b6c1ad14f9a70b0dedb31ac5c60813d7a0adb5017"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "47d32eec023f9d00f16bd5fba49778ad622dca453ec2306e8d1af2daf625b51f"
metafile = true

[[files]]
file = "mods/aether-emissivity.pw.toml"
hash = "71b37e848b677dccc17c05a6a68a0a52f45d055a9f1e168d277946569bbb8a36"
metafile = true

[[files]]
file = "mods/aether-enhanced-extinguishing.pw.toml"
hash = "3ab0e784d15c52edda001697336bc3d7bceb1d016c89b166c77b10f6fb689737"
metafile = true

[[files]]
file = "mods/aether-protect-your-moa.pw.toml"
hash = "68843d86fd6914e4d4766575fb3f63e37fe8b40153539f0c219439980d40fe07"
metafile = true

[[files]]
file = "mods/aether-treasure-reforging.pw.toml"
hash = "c7c9a31368adc4c4d6abfc647f07c1eb70fb6c2be31959b5ca88c109f891860b"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "cc3f6e6e8f1838d16e47cce9241e32176279673efb1438ff4451ccffa9579b14"
metafile = true

[[files]]
file = "mods/all-arrows-infinity-fix.pw.toml"
hash = "a349b5afe6dcdcc40c21a37de5112997d0ea98e79cefadda1520159da796ae89"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "5525cfe500a324b4415516770d584eab9b0f6ca64286c55547b5403e76f63b3b"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "18cf2b63d293ba0738c1073690fbd2c62305b161f76d346a551a66a9bbf8af32"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/aquaculture.pw.toml"
hash = "2cdccc2de0235ccc5d2a0d2c5649c890c52960bc08687620f374d71e4dfb78bd"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/armourers-workshop.pw.toml"
hash = "38fe7e7d3ccf479856998367637e47d3df4d83d0443dceb3a1294683725d3096"
metafile = true

[[files]]
file = "mods/bagus-lib.pw.toml"
hash = "b3a16507ca0190a16529b712bcfa658b796764ae47ee23c99b80316a43d013d6"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "547660bb17452fae6e46504c87eea9e75eeb50de440495cadcee9ad49c6d131d"
metafile = true

[[files]]
file = "mods/beautified-chat-client.pw.toml"
hash = "e2f738262c85b91c8b62cdcc001e0f13bbfee921d5d0c51b628ba464b0df63c5"
metafile = true

[[files]]
file = "mods/beautified-chat-server.pw.toml"
hash = "067c3905b3b6bd4ef5f33b9d79203718c63a5ba4fa1fe2253fa3aa5ca00e0c73"
metafile = true

[[files]]
file = "mods/beautify.pw.toml"
hash = "5e3421b58c8c905e686ed7b63d2fe086fe3265009347ca01aba99f13cb8edca3"
metafile = true

[[files]]
file = "mods/better-modlist.pw.toml"
hash = "5ebc1849da4c78f57b8f4cde4320d5409ea9244e372d50afc6362ee88d66dd50"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "cc2e6dda94a7a6f5487843cafe569d8044bf9482cbf03f062cf4595f1fb05281"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "c9aca350959a8936b054c7164fb55d789ab1e0d38cff2af48b78f70af2bc0c6d"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "f33a4720ef4f315b6d1f778039e9f7bdb8f5ef1b58a57d565c30fd1d8adee207"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "91b81c2bf3b64e458a1fd5100c574244428424da770835f9f4dc3349ab18997b"
metafile = true

[[files]]
file = "mods/cat_jam.pw.toml"
hash = "c5adc29c7b5aa88587ab54f39d654216bb087e767727a182a4bf44f98228ba5c"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8629fe0739a2243641a1a00b103682bcb2741a9295f9eac4c2a2135a867f8442"
metafile = true

[[files]]
file = "mods/chunks-fade-in.pw.toml"
hash = "87b11fbf14f926be2575810a428195d9345b43782d7ba25d5496b3e2fde92226"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2acaff560bbda5741538528a2967355ec86a8f7564adba0b2316989c66892374"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "32ac4c34834d69292990fdd1c04bc10f26de3f8445a92fd32744a2d520c7eb83"
metafile = true

[[files]]
file = "mods/cobblemonextras.pw.toml"
hash = "58825929d4134645ade28edaeeb59348399c2d3a2c0f4015394c0e9933014485"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "cde21d14fcaf9495f0f5b3d8fb298dd60cb12badc21a27414c25ebf11dfb3fe1"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "6742ced22a5d002f0f03a54ccb147c97cf910a1c52dce6f80d58dd69bec54686"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "d901f874a1e09747b8d0d072c38c426eceead1f29c8ba36680f8f0082996b152"
metafile = true

[[files]]
file = "mods/crash-utilities.pw.toml"
hash = "6457e8702c7c3d603e1e35252bf2388db4ec44c875209af3c4364a79f4c1709c"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "14c9c8de75528a9322c3c96b7f706e5057bc5c1bd339f421f208ff6206f90898"
metafile = true

[[files]]
file = "mods/croptopia.pw.toml"
hash = "9aa575969f8a359ac795b4e8754f3423d189d701088e197a7ace68eeaaaa0276"
metafile = true

[[files]]
file = "mods/customskinloader.pw.toml"
hash = "fcd089a8f468ec888297aeb1c0846e1d0eb42e0bb096e1c551b6bd44ea9370c5"
metafile = true

[[files]]
file = "mods/cyanide.pw.toml"
hash = "08ab5ee502b94653263fdfea09b0c58958e9e6adffc45cb35f496cc5a0a6fb8d"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "bd005d9f92131c7c4a88a081aa5368c482eec2cb410d14ab245a2f081e9e1ffb"
metafile = true

[[files]]
file = "mods/display-delight.pw.toml"
hash = "28f531c7efc9e5257235adcb19913ed278f3bc76a36326f28d9fb9303df9e4de"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "fe88386ca7a7c34be094f10e3a012810cec23f21b580dbc1c908cf95a17bf6f8"
metafile = true

[[files]]
file = "mods/epherolib.pw.toml"
hash = "af8104f6a407333ecbefe9edd73ac873a77f59aed959913607ff808812de47d7"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "cd77d7f479a925f2c5147a9e4103a7c35c19292bf3a3144a59ecbb2905ceba62"
metafile = true

[[files]]
file = "mods/explosion-breaks-no-block.pw.toml"
hash = "ef45149b724527d6c01fecd1189b2ec151107ec1221be3aa0fbefbdd383e7b5b"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "9db6b697952d190c3c3fc6024f74713d74a808e5ec85c1adfd3e23ca769cd588"
metafile = true

[[files]]
file = "mods/female-gender-neoforge.pw.toml"
hash = "2e2c305b077eb8c92034838afa52ec7f5eb3163f3883258ca0685de7af65e9e6"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "b5d7571bff8454770fcbba30a4c90d8f020e84d626c731f92d46dc9ecea34d85"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
hash = "939c71e9b7d893e65560ada8a5b7ad0c8f000db400ddbec814e038d2a2cb99c0"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
hash = "2a75b3fb887f2b973ce82a1881ac811eea35dfe194d4e321f3e2565815e94448"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "0580a44f77a6e88c906bce984b369ca757a0a73062203e9ce1a144544ede9c8a"
metafile = true

[[files]]
file = "mods/happy-ghast-legacy.pw.toml"
hash = "148ad0767c2696e220f378394e6a232521f8f255750e9e53a8723d7c6b9dde08"
metafile = true

[[files]]
file = "mods/i18nupdatemod.pw.toml"
hash = "f596d49b8d8a5ce74b39bfb9dd140175ae97b30e822c113cdc5c093926177426"
metafile = true

[[files]]
file = "mods/infinite-trading.pw.toml"
hash = "e5a2b00a5a99de7ed4cf8184a60307afeecc4dce5ae0fb073cef29bef42e9826"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "62cd07874e73d82b29ff6fecd5345ce4b1135ce7ff29f3ef695139be33157483"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "25680ee42912b70c0a0404ebf5b96982ee6942818c12d282888f8a18066f3adf"
metafile = true

[[files]]
file = "mods/just-player-heads.pw.toml"
hash = "f7826df1f2dac2bcca00724f1d84c981d0fff5cfe7b7eb2f589a3a2ceb1c9d5d"
metafile = true

[[files]]
file = "mods/justenoughcharacters.pw.toml"
hash = "22b453921fe14912cc9116a2201c99916003fa7a6ffb80531bc187a45b6e3aa1"
metafile = true

[[files]]
file = "mods/kaleidoscope-doll.pw.toml"
hash = "fe245b289e399266a65851927d9c4daa828e598d72ae497ac0d98e3411c7329c"
metafile = true

[[files]]
file = "mods/keep-my-soil-tilled.pw.toml"
hash = "3bde12aa925f6bf027cf5f2bce1392cb0f3a0498d9d423933d702f2638f16065"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7b8e8af83e8583adc91b2d859e5355f1bd0516a346d2584b8b01c004467d18af"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "c6887c071d6515a39aeb915429304ea9fdae876decde3ad66062c9ba779b16b4"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6f0dcbcffd4400c6cef07f1eeb48cdc25bac0fa01270936feab4c549aff4738e"
metafile = true

[[files]]
file = "mods/modern-ui.pw.toml"
hash = "1b8e7dc5dca00aea85c9f1b42119d9a6e09ec69c62651035149fcfd26f0422e5"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eae3c14c915400de36bf547550f630de727bbf48ae0ce719b99b2ff50ceaab0d"
metafile = true

[[files]]
file = "mods/moreleads.pw.toml"
hash = "d6269258c16a05a64642110e4c80c1d444aeb6756e428102b6c4ca767b54f155"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "42805ef7e224873873d190b0363f2a53dae02530553574f29fab92e258bc0470"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "b4b723e8c39b3737bd276678989e3253a576438155bcef89a4b62ee6947dd301"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/parcool.pw.toml"
hash = "c37ffd7fa4e62e1b68cf6a62baffc712667ed7f60ba542620caa6cdf78ca8be5"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "04ba8a8c91a6c25c42321493a2d233762bb01169fac5fd834e434887cdbf8596"
metafile = true

[[files]]
file = "mods/player-name-tweaks.pw.toml"
hash = "c2a5f879516ee6b9924202b923fe1cdbfe6ad51c342a086a82f461082a14b539"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
hash = "bb53e2c30a71e477476f8964b9a8c5294207969659c755b5c9993bca94139385"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "152769b5dfbb92a836634e315898b23b6a555c60b6f05ddf38c00085f2b784f6"
metafile = true

[[files]]
file = "mods/prefab.pw.toml"
hash = "3b596c6930098e045335e5535aa34d14c57514b4f09a5353270280cf5a934a2a"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "c99c5bac469e8d6ece5aae80f08635e3bbb8367f0c586b6288573c725faefe69"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/repurposed-structures-farmers-delight-compat.pw.toml"
hash = "1b9625747845eac9c4a92135ec74201039b9f7677abbf42bc8b61f51986b5a1a"
metafile = true

[[files]]
file = "mods/repurposed-structures-forge.pw.toml"
hash = "bea60e40fe79a55c4ae9b0c6b7be6d91ababfa352b707cc0268b4757796d716f"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "2c1661e65d47c2942d2c3e926698d0762672224f1925c7f25105b964ce25b093"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/sky-villages.pw.toml"
hash = "65ae5274b963d5b15e22cd3680b2ac6851f3fa5669b3914c496b45148a18a5a7"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "c1e526d3d17cb3563e596d45c7567ed1fe60c31bdc3457f7a747ef8150bd3c1b"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "02b29315d2ec0d055d0ebba1f36879da5bcacc823328a668c7e7340fb2cb03d4"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "c5687771065e4a43266b38018cbdf142b216916dd73aa6532b8282e3d0f06b9c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "a73dfb1bf6884ae786b2def0624dee9010bf121d0b5678b46043d9312f54b501"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "49bccf856ced968a9499d110c302225b7f6d71c415d23f89db44325a72ff638a"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "743b6485780687c9736b9db5753cec0c71c761d75eb9c88a62d8a92b9a0a83bc"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "09c393b303130cefffc1c376ddfdeb869b20db31d3d42d9fa155e13cfc628645"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "593fa7b30ab016aa45be07bd6bef3a9f160ed0f24689850d60bf84995d69b843"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "0e9840c892e4904744e3f3efcd2e17f675c005e372b01532203a25a7de2224de"
metafile = true

[[files]]
file = "mods/teleport-commands.pw.toml"
hash = "4069c2ead5632415da835ba6043097ddf0f0c3ca8a52caad76a20b116217ab4f"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
hash = "b2dd43f9809966eaed8ece9f72ec9ca4f35e8b1d5fd04cb7aa54d847ac9dab91"
metafile = true

[[files]]
file = "mods/title-screen-blobcat.pw.toml"
hash = "ddbd6e994511a8df32a05a5dc25a18dfc58b26388c69d23b75f7ea667579036e"
metafile = true

[[files]]
file = "mods/tofucraftreload.pw.toml"
hash = "95690db68e362a1ebc059b7712355880e00629b601a3ad07e7f47debcabc6ffe"
metafile = true

[[files]]
file = "mods/touhou-little-maid.pw.toml"
hash = "ad51047953ba318591e3f05a2b6c4c499824df7dd2d1aedc1be174ed33936235"
metafile = true

[[files]]
file = "mods/trajectory-estimation.pw.toml"
hash = "02c9ba213d5b2285c7c0d61ee391c597389faedb8525b22a54c9cf208b8d97cf"
metafile = true

[[files]]
file = "mods/waterframes.pw.toml"
hash = "a255c29cb611f60aaad313b223bc424721be5998673002da6b589b2862912621"
metafile = true

[[files]]
file = "mods/watermedia-yt-plugin.pw.toml"
hash = "e0b5d86b63b2aa52bf50d3b58280fed584f8cfef65edc32e7a8b317690e877bc"
metafile = true

[[files]]
file = "mods/watermedia.pw.toml"
hash = "9c14d2011a343872dfa72aee64ef7beb2f9f9e47867807b4b03726cfa8e429b7"
metafile = true

[[files]]
file = "mods/watervision.pw.toml"
hash = "393310e8c75c51eb3143c8ddcdac51917a5d759d428e5b962e4c2b4c8e87bc0e"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "09722fcffb274b44bde74673f2e3ef594f7353884c4e48e4822bcd68e9ff0ed0"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "c02af11f10e1f939de401d5cfe250f92c623c034adf90220df0be6e23f202621"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "9ce52d07c0c3d146a2a44f8bc187138ce7a5558a4e3ab540c86234702b6de274"
metafile = true

[[files]]
file = "mods/world-comment.pw.toml"
hash = "60a0b4603ba9cf3a8d9506a8c96a990e998a4a9002b0dfc7b9adcfce1fdfcc28"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "de999f6cc4c2f344e324b4f331fa9767844c31463c6e8066fcd67b613338ab8c"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
hash = "b2fadce5066f687b312a61723f9c5e568b3f51687497307a981264181e6d930b"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d2038a71aca0eb91088da10a9cafdcf204aba02c97c2c52b485246233e734ba"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "95fbcd74600490b7a6a658f9004f905bbcaeebbce25e23762d7cf06ce5193aab"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "539f362e9e192cf3b2813e0dfdfc51a5e6814129c6e82a9733842529beea6242"
metafile = true

[[files]]
file = "mods/yeetus-experimentus.pw.toml"
hash = "5e25dccab496945a5f19bb82383e0ebf98452ffc14cd25c7e0259cc44312281a"
metafile = true

[[files]]
file = "mods/you-died.pw.toml"
hash = "00c95560c099838ecc9e146154b49179b945d93acb5c60aa8c6d12d0dab9762a"
metafile = true

[[files]]
file = "mods/yuushya-modelling.pw.toml"
hash = "7dd933f59cbc247d0811f3c632ce2fb6d942d9f66d89f6b6cfddc772d70d2281"
metafile = true

[[files]]
file = "mods/yuushya-townscape.pw.toml"
hash = "be623dda8516bbd20d9da1eb7b0ccb4373b068cc83b0788752a743bcdf5b8ae9"
metafile = true

[[files]]
file = "resourcepacks/cubic-sun-moon.pw.toml"
hash = "6d198fcead3ae516d33d9011f3ecf9717a72b963aadea7a6b3ad7f0c7cada070"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "62a05d47482affa433c1f05eb392c95aa72977b07992c42b8a4ee64234d53b99"
metafile = true

[[files]]
file = "resourcepacks/default-hd-128x.pw.toml"
hash = "ad16b778337a3f9014cd46753808d42ec3bc8144c7bbbaed9128c94fc9199e0d"
metafile = true

[[files]]
file = "resourcepacks/faithful-64x.pw.toml"
hash = "f4a9a98cd10ccd11d790e1c264ae2b4110f38f9a7464517d1eb4eea01701c455"
metafile = true

[[files]]
file = "resourcepacks/yuushya-16x.pw.toml"
hash = "ae09123c09b40942742eea5b3651f7d655acb1f3b314e36f0c85072ff1bd0a74"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "71cf0534dd8b064616a6120c2b93023340bc79d2db21a1d9197087b9c9d7eee5"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true

[[files]]
file = "shaderpacks/insanity-shader.pw.toml"
hash = "28f891fb3f12855303ee2b28b095acde264a2fa9b1d25379d9a5e25862af75c9"
metafile = true
