name = "gmgmxbxhwwMCmmmm"
author = "MCSeekeri"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13df7b3ced5f372555058d4944a9bb022246dd07c4bc6193bdf0963e33f22fc1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
