name = "gmgmxbxhwwMCmmmm"
author = "MCSeekeri"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "729ae47b4429b6e3c51f1a557abea9b5d6b05867e0209769ba85a5dd70f24d1b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
