name = "gmgmxbxhwwMCmmmm"
author = "MCSeekeri"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b479ad8d1d6175e6e1ece5c176aed84bcbf6b393f8e1f606f6c97987705c8a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
