name = "FengServerX-NeoForge"
author = "MCSeekeri"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f72df93f4dfa291b60fbbef3fbec9f374bb3159396fec2998f91f6d94ed8d997"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.115"
