name = "FengServerX-NeoForge"
author = "MCSeekeri"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a44efddda578ec1ba00b7bb8ff1ddfee17f211c57136463ed03dfa47eb32f3a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.115"
